version: '3'

services:
  # Serviço que irá rodar o node
  api:
    build: ./server
    container_name: todo_backend
    working_dir: /app/server
    restart: always
    volumes:
      - ./server:/app/server
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    command: npm run start:dev
    environment:
      - MONGO_URI=mongodb://mongodb:27017/todo

  mongodb:
    image: mongo:5.0.7
    container_name: todo_mongodb
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27017:27017