version: '3'

services:
  # serviço que roda o react no vite
  web:
    build: ./web
    container_name: todo_frontend
    working_dir: /app-frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
  # Serviço que irá rodar o node
  api:
    build: ./server
    container_name: todo_backend
    working_dir: /app-backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    command: npm run start:dev
    environment:
      - MONGO_URI=mongodb://mongodb:27017/todo

  mongodb:
    image: mongo:5.0.7
    container_name: todo_mongodb
    platform: linux/x86_64
    restart: always
    ports:
      - 27017:27017